//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AamozishVocab.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Content
    {
        public System.Guid Id { get; set; }
        public System.Guid TypeId { get; set; }
        public Nullable<System.Guid> TranslatorId { get; set; }
        public Nullable<System.Guid> ParentId { get; set; }
        public string Title_En { get; set; }
        public string Title_Hi { get; set; }
        public string Title_Ur { get; set; }
        public string Content_En { get; set; }
        public string Content_Hi { get; set; }
        public string Content_Ur { get; set; }
        public string Translation_En { get; set; }
        public string FootNote_En { get; set; }
        public string FootNote_Hi { get; set; }
        public string FootNote_Ur { get; set; }
        public string Radeef_En { get; set; }
        public string Radeef_Hi { get; set; }
        public string Radeef_Ur { get; set; }
        public Nullable<int> Alignment { get; set; }
        public int Rating { get; set; }
        public int Status { get; set; }
        public bool IsMapped { get; set; }
        public bool IsApproved { get; set; }
        public bool IsLineCountValid { get; set; }
        public bool IsValid { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateModified { get; set; }
        public Nullable<System.DateTime> DatePublished { get; set; }
        public Nullable<System.DateTime> DateLastPublished { get; set; }
        public string SEO_KeywordsEn { get; set; }
        public string SEO_DescriptionEn { get; set; }
        public string SEO_TextEn { get; set; }
        public string SEO_KeywordsHi { get; set; }
        public string SEO_DescriptionHi { get; set; }
        public string SEO_TextHi { get; set; }
        public string SEO_KeywordsUr { get; set; }
        public string SEO_DescriptionUr { get; set; }
        public string SEO_TextUr { get; set; }
        public string SEO_Slug { get; set; }
        public bool IsActive { get; set; }
        public bool IsChanged { get; set; }
        public bool IsDeferred { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.Guid ModifiedBy { get; set; }
        public string UserInfo { get; set; }
        public string SubTitle_En { get; set; }
        public string SubTitle_Hi { get; set; }
        public string SubTitle_Ur { get; set; }
        public string LongRadeef_En { get; set; }
        public string LongRadeef_Hi { get; set; }
        public string LongRadeef_Ur { get; set; }
        public int ShortUrlIndex { get; set; }
        public Nullable<short> Difficulty { get; set; }
        public Nullable<short> Quality { get; set; }
        public Nullable<short> Popularity { get; set; }
        public bool IsTranslation { get; set; }
        public string Explanation_En { get; set; }
        public bool TextType { get; set; }
        public string ContentHtml_En { get; set; }
        public string ContentHtml_Hi { get; set; }
        public string ContentHtml_Ur { get; set; }
        public string TranslationHtml_En { get; set; }
        public string ExplanationHtml_En { get; set; }
        public Nullable<System.Guid> ExplainerId { get; set; }
        public string Explanation_Hi { get; set; }
        public string Explanation_Ur { get; set; }
        public string Translation_Hi { get; set; }
        public string Translation_Ur { get; set; }
        public string TranslationHtml_Hi { get; set; }
        public string TranslationHtml_Ur { get; set; }
        public string ExplanationHtml_Hi { get; set; }
        public string ExplanationHtml_Ur { get; set; }
        public bool HaveBannerWeb { get; set; }
        public bool HaveBannerMobile { get; set; }
        public bool Justified { get; set; }
        public bool Out_of_Copyright_Purview { get; set; }
        public bool Copyright_Permission { get; set; }
    }
}
